#-------------------------------------------------------------------------------
#
# TravisCI Configuration, https://docs.travis-ci.com/.
#
# Supports running npm based test suite on multiple node versions to ensure
# backwards compatibility is retained.
#
#-------------------------------------------------------------------------------
---
language: node_js

# Run scripts without elevated access.
sudo: false

node_js:
  - "8"
  - "9"
  - "10"
  - "11"

cache:
  directories:
    - "node_modules"

before_script:
  # Install npm dependencies and skip dependency audit as we will run this
  # explicitly later.
  - "npm install --no-audit"

script:
  # Ensure returns true even if command not available.
  - "npm audit || true"
  - "npm run test"
