#-------------------------------------------------------------------------------
#
# TravisCI Configuration, https://docs.travis-ci.com/.
#
# Supports running npm based test suite on multiple node versions to ensure
# backwards compatibility is retained.
#
#-------------------------------------------------------------------------------
---
language: node_js

# Run scripts without elevated access.
sudo: false

node_js:
  - "10"
  - "12"

cache: "yarn"

before_script:
  # Install yarn dependencies and skip dependency audit as we will run this
  # explicitly later.
  - "yarn install --no-audit"

script:
  - "yarn audit"
  - "yarn build"
  - "yarn lint"
  - "yarn test"
